package view.viewItems.ItemBox;

public enum SelectKind {

	TILEITEM,
	VIEWTILE, EVENT, DOOR, VIEWDOOR, TRIGGER, TOKEN, VIEWTOKEN, VIEWMONSTER, MONSTER, MODIFIER
	,VALUE, BOOLEANVALUE, GENERATOR, MULTITRIGGER;
	
}
